Repository nginx/ansible-role-nginx, pull requests merged in 2018-04, with the labels that each got.

#14 Fix template path issues
  tasks/conf/push-config.yml
  tasks/conf/setup-status.yml
  tasks/conf/template-config.yml
Labels: bug, enhancement

#25 Check if configuration file is defined
  tasks/conf/push-config.yml
  tasks/conf/template-config.yml
Labels: bug

#22 Test role across multiple distributions
  .travis.yml
  tests/dockerfiles/Dockerfile.centos-6
  tests/dockerfiles/Dockerfile.centos-7
  tests/dockerfiles/Dockerfile.debian-jessie
  tests/dockerfiles/Dockerfile.debian-stretch
  tests/dockerfiles/Dockerfile.ubuntu-trusty
  tests/dockerfiles/Dockerfile.ubuntu-xenial
  tests/files/http/default.conf
  tests/files/nginx.conf
  tests/inventory
  tests/playbooks/nginx-opensource.yml
  tests/playbooks/nginx-push.yml
  tests/playbooks/nginx-template.yml
Labels: enhancement
