Repository nginx/ansible-role-nginx, pull requests merged in 2019-04, with the labels that each got.

#117 Added support for try_files
  defaults/main.yml
  templates/http/default.conf.j2
  templates/stream/default.conf.j2
Labels: enhancement

#114 Add ssl_dhparam option
  README.md
  defaults/main.yml
  templates/http/default.conf.j2
Labels: enhancement

#113 Amplify installation fixes
  tasks/amplify/install-amplify.yml
  tasks/main.yml
Labels: bug

#119 Reference the correct variable name in comment
  README.md
Labels: documentation

#121 Http auth req additions - issue 120
  README.md
  defaults/main.yml
  tasks/modules/install-modules.yml
  templates/http/default.conf.j2
  tests/playbooks/nginx-http-template.yml
Labels: enhancement
