Repository nginx/ansible-role-nginx, pull requests merged in 2019-10, with the labels that each got.

#169 Add templating options to logs
  README.md
  defaults/main.yml
  molecule/template_module/playbook.yml
  templates/http/default.conf.j2
  templates/nginx.conf.j2
Labels: enhancement

#162 Fix module installation when with plus
  tasks/main.yml
  tasks/plus/install-plus.yml
Labels: bug

#172 Create Travis build matrix for molecule builds
  .travis.yml
Labels: enhancement

#171 Update README
  README.md
  tests/playbooks/nginx-http-template.yml
Labels: documentation

#174 Reload NGINX after cleaning up configs
  tasks/conf/cleanup-config.yml
Labels: bug, enhancement

#167 Add custom_options
  README.md
  defaults/main.yml
  molecule/template_module/playbook.yml
  templates/http/default.conf.j2
  templates/nginx.conf.j2
  templates/stream/default.conf.j2
Labels: enhancement
