Repository nginx/ansible-role-nginx, pull requests merged in 2019-12, with the labels that each got.

#200 Split defaults/main.yml to more files in directory defaults/main
  README.md
  defaults/main/amplify.yml
  defaults/main/bsd.yml
  defaults/main/controller.yml
  defaults/main/linux.yml
  defaults/main/main.yml
  defaults/main/template.yml
  defaults/main/unit.yml
  defaults/main/upload.yml
Labels: enhancement

#202 Add option to use/update to the latest version of NGINX
  defaults/main/main.yml
  tasks/opensource/install-oss-bsd.yml
  tasks/opensource/install-oss-linux.yml
  tasks/opensource/setup-alpine.yml
  tasks/opensource/setup-debian.yml
  tasks/opensource/setup-redhat.yml
  tasks/opensource/setup-suse.yml
  tasks/plus/install-plus-bsd.yml
  tasks/plus/install-plus-linux.yml
Labels: enhancement

#203 Let users define the target https redirect variable
  defaults/main/template.yml
  templates/http/default.conf.j2
Labels: bug

#204 Delete NGINX Plus repository when license is deleted
  defaults/main/main.yml
  tasks/main.yml
  tasks/plus/delete-license.yml
  tasks/plus/install-plus-bsd.yml
  tasks/plus/install-plus-linux.yml
  tasks/plus/setup-alpine.yml
  tasks/plus/setup-bsd.yml
  tasks/plus/setup-debian.yml
  tasks/plus/setup-license.yml
  tasks/plus/setup-redhat.yml
  tasks/plus/setup-suse.yml
Labels: bug

#205 Add new method to install the NGINX Controller agent
  README.md
  defaults/main/controller.yml
  tasks/controller/install-controller.yml
  tasks/controller/setup-controller-instance.yml
  tasks/controller/setup-controller-repository.yml
  tasks/controller/setup-debian.yml
  tasks/controller/setup-redhat.yml
  tasks/main.yml
Labels: enhancement

#206 Improve documentation
  .github/pull_request_template.md
  .yamllint
  CONTRIBUTING.md
  README.md
  defaults/main/template.yml
Labels: enhancement

#211 apt update (after installation from the nginx repo) gives an error #210
  tasks/opensource/setup-debian.yml
Labels: bug, enhancement

#212 Only add Debian repositories when installing role in amd64 archs
  tasks/amplify/setup-debian.yml
  tasks/controller/setup-controller-repository.yml
  tasks/plus/setup-debian.yml
  tasks/unit/setup-debian.yml
Labels: bug, enhancement
