Repository nginx/ansible-role-nginx, pull requests merged in 2019-11, with the labels that each got.

#177 Add option to specify the version of NGINX to install
  defaults/main.yml
  molecule/default/molecule.yml
  molecule/default/playbook.yml
  molecule/stable_push/molecule.yml
  molecule/template_module/molecule.yml
  molecule/unit/molecule.yml
  tasks/opensource/install-oss.yml
  tasks/plus/install-plus.yml
Labels: enhancement

#176 Add support for multiple rewrite directives as per nginx conf
  README.md
  defaults/main.yml
  templates/http/default.conf.j2
Labels: enhancement

#184 Add variable to set location of NGINX status conf file
  README.md
  defaults/main.yml
  tasks/conf/setup-status.yml
  tasks/conf/template-config.yml
  templates/http/api.conf.j2
Labels: bug

#182 Separate installation of Linux and BSD
  defaults/main.yml
  handlers/main.yml
  tasks/opensource/install-oss-bsd.yml
  tasks/opensource/install-oss-linux.yml
  tasks/opensource/install-oss.yml
  tasks/opensource/setup-freebsd.yml
Labels: enhancement

#186 Tags added to main.yml
  tasks/main.yml
Labels: enhancement

#188 Add proxy_sent_timeout and make upstream zones optional
  defaults/main.yml
  templates/http/default.conf.j2
Labels: enhancement

#190 Fix OSS Alpine installation and add Alpine test coverage
  defaults/main.yml
  molecule/common/Dockerfile.j2
  molecule/default/molecule.yml
  molecule/default/playbook.yml
  tasks/keys/apk-key.yml
  tasks/opensource/install-oss-linux.yml
  tasks/opensource/setup-alpine.yml
  tasks/opensource/setup-debian.yml
  tasks/opensource/setup-redhat.yml
  tasks/opensource/setup-suse.yml
  tasks/plus/install-plus.yml
Labels: bug, enhancement

#191 Add Alpine tests to all molecule scenarios
  .travis.yml
  molecule/module/molecule.yml
  molecule/stable_push/molecule.yml
  molecule/template/molecule.yml
  molecule/unit/molecule.yml
  molecule/unit/playbook.yml
  tasks/opensource/install-oss-linux.yml
  tasks/opensource/setup-alpine.yml
  tasks/opensource/setup-debian.yml
  tasks/opensource/setup-redhat.yml
  tasks/opensource/setup-suse.yml
Labels: enhancement

#195 Add vi and emacs autosave files to .gitignore
  .gitignore
Labels: enhancement

#192 Added proxy_cache_valid support
  README.md
  defaults/main.yml
  molecule/template/playbook.yml
  templates/http/default.conf.j2
Labels: enhancement

#194 Add multiple servers for reverse proxy template
  README.md
  defaults/main.yml
  molecule/template/playbook.yml
  tasks/conf/template-config.yml
  templates/http/default.conf.j2
Labels: enhancement

#197 Add tcp_nopush and tcp_nodelay vars
  README.md
  defaults/main.yml
  templates/nginx.conf.j2
Labels: enhancement

#193 NGINX Plus separate installation of Linux and FreeBSD
  defaults/main.yml
  tasks/plus/install-plus-bsd.yml
  tasks/plus/install-plus-linux.yml
  tasks/plus/install-plus.yml
  tasks/plus/setup-freebsd.yml
  tasks/prerequisites/install-prerequisites.yml
  tasks/prerequisites/setup-freebsd.yml
Labels: enhancement

#199 Don't enforce the use of lb_method in upstream.
  templates/http/default.conf.j2
Labels: enhancement

#201 Configure min_ansible_version
  README.md
  meta/main.yml
Labels: enhancement
