Repository nginx/ansible-role-nginx, pull requests merged in 2020-06, with the labels that each got.

#257 Update docs
  .github/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  molecule/common/playbook_default.yml
  molecule/common/playbook_template.yml
Labels: documentation

#258 Add support for Ubuntu Focal
  .travis.yml
  README.md
  defaults/main/main.yml
  meta/main.yml
  molecule/common/Dockerfile.j2
  molecule/common/playbook_default.yml
  molecule/common/playbook_default_verifier.yml
  molecule/default/molecule.yml
  molecule/module/molecule.yml
  molecule/source/molecule.yml
  molecule/stable_push/molecule.yml
  molecule/template/molecule.yml
  molecule/unit/molecule.yml
  tasks/opensource/setup-source.yml
Labels: enhancement

#259 Remove semicolons from custom_options
  molecule/common/playbook_template.yml
  templates/http/default.conf.j2
  templates/nginx.conf.j2
  templates/stream/default.conf.j2
Labels: bug

#262 Improve config cleanup tasks
  defaults/main/main.yml
  molecule/common/playbook_default_verifier.yml
  molecule/common/playbook_module.yml
  molecule/common/test_module/test_default.py
  tasks/conf/cleanup-config.yml
Labels: bug

#208 Add events_custom_options to template.yml defaults
  defaults/main/template.yml
  molecule/common/playbook_template.yml
Labels: bug

#264 Add CentOS/RedHat yum repository module_hotfixes option
  molecule/common/playbook_default.yml
  tasks/opensource/setup-redhat.yml
Labels: bug, improvement

#266 Add support for unix upstreams
  molecule/common/playbook_default.yml
  molecule/common/playbook_template.yml
  templates/http/default.conf.j2
Labels: bug, enhancement

#265 Add `access_log` to status and API configuration files
  defaults/main/template.yml
  molecule/common/playbook_template.yml
  tasks/conf/setup-status.yml
  tasks/conf/template-config.yml
  templates/http/api.conf.j2
Labels: enhancement

#267 Add PID templating option
  defaults/main/template.yml
  molecule/common/playbook_template.yml
  templates/nginx.conf.j2
Labels: enhancement

#270 Adding nginx_main_template.http_custom_includes
  defaults/main/template.yml
  molecule/common/playbook_template.yml
  templates/nginx.conf.j2
Labels: enhancement

#274 Fix error when http_demo_conf undefined
  templates/http/default.conf.j2
Labels: bug

#272 Triple S!!! Speed, Systemd and Selinux
  README.md
  defaults/main/main.yml
  defaults/main/systemd.yml
  files/services/nginx.override.conf
  handlers/main.yml
  molecule/common/playbook_default.yml
  molecule/common/playbook_module.yml
  molecule/common/playbook_template.yml
  tasks/amplify/install-amplify.yml
  tasks/keys/setup-keys.yml
  tasks/main.yml
  tasks/modules/install-modules.yml
  tasks/opensource/install-oss-linux.yml
  tasks/opensource/install-oss.yml
  tasks/plus/delete-license.yml
  tasks/plus/install-plus-bsd.yml
  tasks/plus/install-plus-linux.yml
  tasks/plus/install-plus.yml
  tasks/prerequisites/install-prerequisites.yml
  tasks/prerequisites/setup-alpine.yml
  tasks/prerequisites/setup-debian.yml
  tasks/prerequisites/setup-freebsd.yml
  tasks/prerequisites/setup-redhat.yml
  tasks/prerequisites/setup-selinux.yml
  tasks/prerequisites/setup-suse.yml
  tasks/prerequisites/setup-systemd.yml
  tasks/unit/install-unit.yml
  templates/selinux/nginx-plus-module.te.j2
  templates/services/nginx.service.override.conf.j2
Labels: enhancement

#277 Add default values for PID and error log
  templates/nginx.conf.j2
Labels: bug
