Repository nginx/ansible-role-nginx, pull requests merged in 2020-07, with the labels that each got.

#276 Add option for custom error pages
  defaults/main/template.yml
  molecule/common/playbook_template.yml
  templates/http/default.conf.j2
Labels: enhancement

#278 Add support for down parameter for upstreams
  molecule/common/playbook_template.yml
  templates/http/default.conf.j2
  templates/stream/default.conf.j2
Labels: enhancement

#279 Flush handlers before running `nginx -T` and setting up logrotate
  tasks/conf/logrotate.yml
  tasks/main.yml
Labels: bug

#280 Remove root HTML tasks from source install
  molecule/common/playbook_source.yml
  tasks/opensource/setup-source.yml
Labels: enhancement

#281 Remove arch descriptor from Debian/Ubuntu src repo
  tasks/opensource/setup-debian.yml
  tasks/unit/setup-debian.yml
Labels: bug

#282 Replace `with_items` with `loop`
  tasks/modules/install-geoip.yml
  tasks/modules/install-njs.yml
  tasks/opensource/setup-debian.yml
  tasks/plus/setup-license.yml
  tasks/unit/install-modules.yml
  tasks/unit/setup-debian.yml
Labels: improvement

#283 Update docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: enhancement

#284 Add separate variables for installing and configuring NGINX
  CHANGELOG.md
  defaults/main/linux.yml
  defaults/main/main.yml
  molecule/common/playbook_default.yml
  tasks/main.yml
Labels: feature

#285 Replace Molecule's Python verifier with the Ansible verifier
  .travis.yml
  README.md
  molecule/common/playbooks/default_converge.yml
  molecule/common/playbooks/default_verify.yml
  molecule/common/playbooks/module_converge.yml
  molecule/common/playbooks/module_verify.yml
  molecule/common/playbooks/source_converge.yml
  molecule/common/playbooks/source_verify.yml
  molecule/common/playbooks/stable_push_converge.yml
  molecule/common/playbooks/stable_push_verify.yml
  molecule/common/playbooks/template_converge.yml
  molecule/common/playbooks/template_verify.yml
  molecule/common/playbooks/unit_converge.yml
  molecule/common/test_default/test_default.py
  molecule/common/test_module/test_default.py
  molecule/common/test_source/test_default.py
  molecule/common/test_stable_push/test_default.py
  molecule/common/test_template/test_default.py
  molecule/default/molecule.yml
  molecule/default_alpine/molecule.yml
  molecule/default_centos/molecule.yml
  molecule/module/molecule.yml
  molecule/module_alpine/molecule.yml
  molecule/module_centos/molecule.yml
  molecule/source/molecule.yml
  molecule/source_alpine/molecule.yml
  molecule/source_centos/molecule.yml
  molecule/stable_push/molecule.yml
  molecule/stable_push_alpine/molecule.yml
  molecule/stable_push_centos/molecule.yml
  molecule/template/molecule.yml
  molecule/template_alpine/molecule.yml
  molecule/template_centos/molecule.yml
  molecule/unit/molecule.yml
  molecule/unit_alpine/molecule.yml
  molecule/unit_centos/molecule.yml
Labels: enhancement

#287 Improve support for listen and ssl directives in stream contexts
  CHANGELOG.md
  defaults/main/template.yml
  molecule/common/playbooks/template_converge.yml
  templates/stream/default.conf.j2
Labels: enhancement

#288 Refactor status templating
  CHANGELOG.md
  defaults/main/template.yml
  molecule/common/playbooks/template_converge.yml
  tasks/conf/setup-status.yml
  tasks/conf/template-config.yml
  tasks/main.yml
  templates/http/api.conf.j2
  templates/http/status.conf.j2
Labels: enhancement

#290 Cleanup source install and remove shell module tasks
  molecule/common/playbooks/source_converge.yml
  tasks/opensource/setup-source.yml
  tasks/prerequisites/setup-debian.yml
Labels: enhancement

#291 Add option to remove a specific list of files
  defaults/main/main.yml
  molecule/common/playbooks/module_converge.yml
  tasks/conf/cleanup-config.yml
Labels: enhancement

#292 Add experimental support for Ubuntu focal
  defaults/main/amplify.yml
  defaults/main/template.yml
  tasks/amplify/setup-debian.yml
  tasks/keys/setup-keys.yml
  tasks/modules/install-geoip.yml
  tasks/modules/install-modules.yml
  tasks/opensource/install-oss-bsd.yml
  tasks/opensource/install-oss-linux.yml
  tasks/opensource/setup-source.yml
  tasks/prerequisites/setup-freebsd.yml
  tasks/prerequisites/setup-selinux.yml
  tasks/prerequisites/setup-systemd.yml
Labels: enhancement

#293 Improve formatting
  .github/pull_request_template.md
  CHANGELOG.md
  README.md
  tasks/main.yml
  tasks/opensource/install-oss-bsd.yml
  tasks/opensource/setup-redhat.yml
  tasks/opensource/setup-source.yml
  tasks/plus/delete-license.yml
  tasks/plus/install-plus-linux.yml
  tasks/plus/setup-license.yml
  tasks/prerequisites/setup-debian.yml
Labels: enhancement
