Repository nginx/ansible-role-nginx, pull requests merged in 2020-08, with the labels that each got.

#299 Add `default_type` templating option
  defaults/main/template.yml
  molecule/common/playbooks/template_converge.yml
  templates/nginx.conf.j2
Labels: enhancement

#306 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#302 Run logrotate only logrotate config changes
  handlers/main.yml
  tasks/conf/logrotate.yml
Labels: enhancement

#307 Update docs
  CHANGELOG.md
  README.md
Labels: documentation

#309 Update Ansible to 2.9.12 and explicitly set mode on relevant tasks
  .travis.yml
  CHANGELOG.md
  README.md
  defaults/main/linux.yml
  handlers/main.yml
  molecule/common/playbooks/module_verify.yml
  molecule/common/playbooks/stable_push_verify.yml
  molecule/common/playbooks/template_converge.yml
  molecule/common/playbooks/template_verify.yml
  tasks/amplify/install-amplify.yml
  tasks/amplify/setup-debian.yml
  tasks/amplify/setup-redhat.yml
  tasks/conf/logrotate.yml
  tasks/conf/template-config.yml
  tasks/conf/upload-config.yml
  tasks/keys/apk-key.yml
  tasks/opensource/install-oss-linux.yml
  tasks/opensource/setup-debian.yml
  tasks/opensource/setup-redhat.yml
  tasks/opensource/setup-source.yml
  tasks/plus/install-plus-linux.yml
  tasks/plus/setup-bsd.yml
  tasks/plus/setup-debian.yml
  tasks/plus/setup-license.yml
  tasks/plus/setup-redhat.yml
  tasks/plus/setup-suse.yml
  tasks/prerequisites/setup-selinux.yml
  tasks/prerequisites/setup-systemd.yml
  tasks/unit/setup-debian.yml
  tasks/unit/setup-redhat.yml
Labels: improvement
