Repository nginx/ansible-role-nginx, pull requests merged in 2021-06, with the labels that each got.

#414 Replace "yes"/"no" boolean values with "true"/"false"
  .github/workflows/galaxy.yml
  .github/workflows/molecule.yml
  .github/workflows/release-drafter.yml
  .yamllint
  CHANGELOG.md
  handlers/main.yml
  molecule/default/verify.yml
  molecule/module/verify.yml
  molecule/plus/prepare.yml
  molecule/plus/verify.yml
  molecule/source/verify.yml
  tasks/amplify/install-amplify.yml
  tasks/amplify/setup-debian.yml
  tasks/amplify/setup-redhat.yml
  tasks/config/debug-output.yml
  tasks/keys/setup-keys.yml
  tasks/main.yml
  tasks/opensource/install-alpine.yml
  tasks/opensource/install-bsd.yml
  tasks/opensource/install-debian.yml
  tasks/opensource/install-redhat.yml
  tasks/opensource/install-source.yml
  tasks/opensource/install-suse.yml
  tasks/plus/install-debian.yml
  tasks/plus/install-freebsd.yml
  tasks/plus/install-redhat.yml
  tasks/plus/install-suse.yml
  tasks/plus/setup-license.yml
  tasks/prerequisites/install-dependencies.yml
  tasks/prerequisites/setup-selinux.yml
Labels: enhancement

#415 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#418 Ignore Ansible lint warning
  tasks/main.yml
Labels: enhancement, skip-changelog

#419 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#420 Add 'nginx_manage_repo' feature flag and defaults
  CHANGELOG.md
  defaults/main/main.yml
  tasks/opensource/install-alpine.yml
  tasks/opensource/install-debian.yml
  tasks/opensource/install-redhat.yml
  tasks/opensource/install-suse.yml
  tasks/plus/install-alpine.yml
  tasks/plus/install-debian.yml
  tasks/plus/install-freebsd.yml
  tasks/plus/install-redhat.yml
  tasks/plus/install-suse.yml
Labels: feature
