Repository nginx/ansible-role-nginx, pull requests merged in 2021-03, with the labels that each got.

#375 Incorrect setup of Systemd restart value
  CHANGELOG.md
  templates/services/nginx.service.override.conf.j2
Labels: bug

#378 Change NGINX config check handler directory
  CHANGELOG.md
  handlers/main.yml
Labels: bug

#381 Update Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: enhancement

#382 Add explicit Jinja2 requirement
  .github/workflows/requirements/requirements_molecule.txt
  CHANGELOG.md
  README.md
Labels: feature

#383 Tweak Molecule tests to account for the current supported platforms
  CHANGELOG.md
  README.md
  meta/main.yml
  molecule/default/converge.yml
  molecule/default/molecule.yml
  molecule/module/molecule.yml
  molecule/plus/molecule.yml
  molecule/source/molecule.yml
Labels: enhancement
