Repository nginx/ansible-role-nginx, pull requests merged in 2022-06, with the labels that each got.

#517 Add support for RHEL9
  CHANGELOG.md
  README.md
  meta/main.yml
  molecule/default/molecule.yml
  molecule/downgrade/molecule.yml
  molecule/downgrade/prepare.yml
  molecule/module/molecule.yml
  molecule/plus/molecule.yml
  molecule/source/molecule.yml
  molecule/uninstall/molecule.yml
  molecule/uninstall_plus/molecule.yml
  molecule/upgrade/molecule.yml
  molecule/upgrade/prepare.yml
  tasks/modules/install-modules.yml
Labels: feature

#522 NGINX Plus does not yet support RHEL 9
  molecule/plus/molecule.yml
  molecule/uninstall_plus/molecule.yml
Labels: bug

#524 Add Alpine Linux 3.16 as a supported platform
  CHANGELOG.md
  README.md
  molecule/default/molecule.yml
  molecule/module/molecule.yml
  molecule/source/molecule.yml
  molecule/uninstall/molecule.yml
Labels: feature

#527 Support the latest NGINX Plus distro updates
  CHANGELOG.md
  README.md
  molecule/plus/molecule.yml
  molecule/uninstall_plus/molecule.yml
Labels: feature

#528 Add Ubuntu jammy to downgrade and upgrade tests
  molecule/downgrade/converge.yml
  molecule/downgrade/molecule.yml
  molecule/downgrade/prepare.yml
  molecule/downgrade/verify.yml
  molecule/upgrade/molecule.yml
  molecule/upgrade/prepare.yml
Labels: tests
