Repository nginx/ansible-role-nginx, pull requests merged in 2022-04, with the labels that each got.

#504 Streamline configuring SELinux
  CHANGELOG.md
  defaults/main/selinux.yml
  molecule/default/converge.yml
  tasks/prerequisites/setup-selinux.yml
  templates/selinux/nginx-plus-module.te.j2
Labels: enhancement

#505 Add `TimeoutStartSec` parameter
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
  defaults/main/systemd.yml
  templates/services/nginx.service.override.conf.j2
Labels: enhancement, dependencies

#506 Bump `community.general` collection
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#508 Ensure `gpg-agent` is installed on Ubuntu
  CHANGELOG.md
  vars/main.yml
Labels: bug
