Repository nginx/ansible-role-nginx, pull requests merged in 2022-02, with the labels that each got.

#487 Add GPG key to Focal apt repo setup
  CHANGELOG.md
  tasks/amplify/setup-debian.yml
Labels: bug

#491 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#492 Use Python 3 in NGINX Amplify when possible
  CHANGELOG.md
  README.md
  tasks/amplify/install-amplify.yml
  tasks/amplify/setup-debian.yml
  tasks/amplify/setup-redhat.yml
Labels: feature
